const ESCROW_STATUS = Object.freeze({
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  FUNDS_HELD_IN_ESCROW: 'FUNDS_HELD_IN_ESCROW',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED',
  FUNDS_RELEASED: 'FUNDS_RELEASED',
  DISPUTED: 'DISPUTED',
  REFUNDED: 'REFUNDED',
  CANCELLED: 'CANCELLED'
});

const VALID_ESCROW_TRANSITIONS = Object.freeze({
  [ESCROW_STATUS.PENDING_PAYMENT]: [ESCROW_STATUS.FUNDS_HELD_IN_ESCROW, ESCROW_STATUS.CANCELLED],
  [ESCROW_STATUS.FUNDS_HELD_IN_ESCROW]: [ESCROW_STATUS.DISPATCHED, ESCROW_STATUS.REFUNDED, ESCROW_STATUS.CANCELLED],
  [ESCROW_STATUS.DISPATCHED]: [ESCROW_STATUS.DELIVERED, ESCROW_STATUS.DISPUTED],
  [ESCROW_STATUS.DELIVERED]: [ESCROW_STATUS.FUNDS_RELEASED, ESCROW_STATUS.DISPUTED],
  [ESCROW_STATUS.FUNDS_RELEASED]: [],
  [ESCROW_STATUS.DISPUTED]: [ESCROW_STATUS.FUNDS_RELEASED, ESCROW_STATUS.DELIVERED, ESCROW_STATUS.REFUNDED],
  [ESCROW_STATUS.REFUNDED]: [],
  [ESCROW_STATUS.CANCELLED]: []
});

const assertEscrowTransition = (from, to) => {
  const allowed = VALID_ESCROW_TRANSITIONS[from] || [];
  if (!allowed.includes(to)) {
    throw new Error(`Invalid escrow transition from ${from} to ${to}`);
  }
};

const isValidEscrowTransition = (from, to) => {
  const allowed = VALID_ESCROW_TRANSITIONS[from] || [];
  return allowed.includes(to);
};

module.exports = {
  ESCROW_STATUS,
  VALID_ESCROW_TRANSITIONS,
  assertEscrowTransition,
  isValidEscrowTransition
};

